// ═══════════════════════════════════════════════════════════════
// FIFA Matrix — Annexe C: 495 combinations for best thirds
// Generated from official Annexe_C.csv
//
// Key: sorted group letters of the 8 qualifying thirds
// Value: [1A, 1B, 1D, 1E, 1G, 1I, 1K, 1L] = group letter of third assigned
// ═══════════════════════════════════════════════════════════════

const FIFA_MATRIX: Record<string, string[]> = {
  'ABCDEFGH': ['H','G','B','C','A','F','D','E'], // Option 495
  'ABCDEFGI': ['C','G','B','D','A','F','E','I'], // Option 494
  'ABCDEFGJ': ['C','G','B','D','A','F','E','J'], // Option 493
  'ABCDEFGK': ['C','G','B','D','A','F','E','K'], // Option 492
  'ABCDEFGL': ['C','G','B','D','A','F','L','E'], // Option 491
  'ABCDEFHI': ['H','E','B','C','A','F','D','I'], // Option 490
  'ABCDEFHJ': ['H','J','B','C','A','F','D','E'], // Option 489
  'ABCDEFHK': ['H','E','B','C','A','F','D','K'], // Option 488
  'ABCDEFHL': ['H','F','B','C','A','D','L','E'], // Option 487
  'ABCDEFIJ': ['C','J','B','D','A','F','E','I'], // Option 486
  'ABCDEFIK': ['C','E','B','D','A','F','I','K'], // Option 485
  'ABCDEFIL': ['C','E','B','D','A','F','L','I'], // Option 484
  'ABCDEFJK': ['C','J','B','D','A','F','E','K'], // Option 483
  'ABCDEFJL': ['C','J','B','D','A','F','L','E'], // Option 482
  'ABCDEFKL': ['C','E','B','D','A','F','L','K'], // Option 481
  'ABCDEGHI': ['H','G','B','C','A','D','E','I'], // Option 480
  'ABCDEGHJ': ['H','G','B','C','A','D','E','J'], // Option 479
  'ABCDEGHK': ['H','G','B','C','A','D','E','K'], // Option 478
  'ABCDEGHL': ['H','G','B','C','A','D','L','E'], // Option 477
  'ABCDEGIJ': ['E','G','B','C','A','D','I','J'], // Option 476
  'ABCDEGIK': ['E','G','B','C','A','D','I','K'], // Option 475
  'ABCDEGIL': ['E','G','B','C','A','D','L','I'], // Option 474
  'ABCDEGJK': ['E','G','B','C','A','D','J','K'], // Option 473
  'ABCDEGJL': ['E','G','B','C','A','D','L','J'], // Option 472
  'ABCDEGKL': ['E','G','B','C','A','D','L','K'], // Option 471
  'ABCDEHIJ': ['H','J','B','C','A','D','E','I'], // Option 470
  'ABCDEHIK': ['H','E','B','C','A','D','I','K'], // Option 469
  'ABCDEHIL': ['H','E','B','C','A','D','L','I'], // Option 468
  'ABCDEHJK': ['H','J','B','C','A','D','E','K'], // Option 467
  'ABCDEHJL': ['H','J','B','C','A','D','L','E'], // Option 466
  'ABCDEHKL': ['H','E','B','C','A','D','L','K'], // Option 465
  'ABCDEIJK': ['E','J','B','C','A','D','I','K'], // Option 464
  'ABCDEIJL': ['E','J','B','C','A','D','L','I'], // Option 463
  'ABCDEIKL': ['E','I','B','C','A','D','L','K'], // Option 462
  'ABCDEJKL': ['E','J','B','C','A','D','L','K'], // Option 461
  'ABCDFGHI': ['H','G','B','C','A','F','D','I'], // Option 460
  'ABCDFGHJ': ['H','G','B','C','A','F','D','J'], // Option 459
  'ABCDFGHK': ['H','G','B','C','A','F','D','K'], // Option 458
  'ABCDFGHL': ['C','G','B','D','A','F','L','H'], // Option 457
  'ABCDFGIJ': ['C','G','B','D','A','F','I','J'], // Option 456
  'ABCDFGIK': ['C','G','B','D','A','F','I','K'], // Option 455
  'ABCDFGIL': ['C','G','B','D','A','F','L','I'], // Option 454
  'ABCDFGJK': ['C','G','B','D','A','F','J','K'], // Option 453
  'ABCDFGJL': ['C','G','B','D','A','F','L','J'], // Option 452
  'ABCDFGKL': ['C','G','B','D','A','F','L','K'], // Option 451
  'ABCDFHIJ': ['H','J','B','C','A','F','D','I'], // Option 450
  'ABCDFHIK': ['H','F','B','C','A','D','I','K'], // Option 449
  'ABCDFHIL': ['H','F','B','C','A','D','L','I'], // Option 448
  'ABCDFHJK': ['H','J','B','C','A','F','D','K'], // Option 447
  'ABCDFHJL': ['C','J','B','D','A','F','L','H'], // Option 446
  'ABCDFHKL': ['H','F','B','C','A','D','L','K'], // Option 445
  'ABCDFIJK': ['C','J','B','D','A','F','I','K'], // Option 444
  'ABCDFIJL': ['C','J','B','D','A','F','L','I'], // Option 443
  'ABCDFIKL': ['C','I','B','D','A','F','L','K'], // Option 442
  'ABCDFJKL': ['C','J','B','D','A','F','L','K'], // Option 441
  'ABCDGHIJ': ['H','G','B','C','A','D','I','J'], // Option 440
  'ABCDGHIK': ['H','G','B','C','A','D','I','K'], // Option 439
  'ABCDGHIL': ['H','G','B','C','A','D','L','I'], // Option 438
  'ABCDGHJK': ['H','G','B','C','A','D','J','K'], // Option 437
  'ABCDGHJL': ['H','G','B','C','A','D','L','J'], // Option 436
  'ABCDGHKL': ['H','G','B','C','A','D','L','K'], // Option 435
  'ABCDGIJK': ['C','J','B','D','A','G','I','K'], // Option 434
  'ABCDGIJL': ['C','J','B','D','A','G','L','I'], // Option 433
  'ABCDGIKL': ['I','G','B','C','A','D','L','K'], // Option 432
  'ABCDGJKL': ['C','J','B','D','A','G','L','K'], // Option 431
  'ABCDHIJK': ['H','J','B','C','A','D','I','K'], // Option 430
  'ABCDHIJL': ['H','J','B','C','A','D','L','I'], // Option 429
  'ABCDHIKL': ['H','I','B','C','A','D','L','K'], // Option 428
  'ABCDHJKL': ['H','J','B','C','A','D','L','K'], // Option 427
  'ABCDIJKL': ['I','J','B','C','A','D','L','K'], // Option 426
  'ABCEFGHI': ['H','G','B','C','A','F','E','I'], // Option 425
  'ABCEFGHJ': ['H','G','B','C','A','F','E','J'], // Option 424
  'ABCEFGHK': ['H','G','B','C','A','F','E','K'], // Option 423
  'ABCEFGHL': ['H','G','B','C','A','F','L','E'], // Option 422
  'ABCEFGIJ': ['E','G','B','C','A','F','I','J'], // Option 421
  'ABCEFGIK': ['E','G','B','C','A','F','I','K'], // Option 420
  'ABCEFGIL': ['E','G','B','C','A','F','L','I'], // Option 419
  'ABCEFGJK': ['E','G','B','C','A','F','J','K'], // Option 418
  'ABCEFGJL': ['E','G','B','C','A','F','L','J'], // Option 417
  'ABCEFGKL': ['E','G','B','C','A','F','L','K'], // Option 416
  'ABCEFHIJ': ['H','J','B','C','A','F','E','I'], // Option 415
  'ABCEFHIK': ['H','E','B','C','A','F','I','K'], // Option 414
  'ABCEFHIL': ['H','E','B','C','A','F','L','I'], // Option 413
  'ABCEFHJK': ['H','J','B','C','A','F','E','K'], // Option 412
  'ABCEFHJL': ['H','J','B','C','A','F','L','E'], // Option 411
  'ABCEFHKL': ['H','E','B','C','A','F','L','K'], // Option 410
  'ABCEFIJK': ['E','J','B','C','A','F','I','K'], // Option 409
  'ABCEFIJL': ['E','J','B','C','A','F','L','I'], // Option 408
  'ABCEFIKL': ['E','I','B','C','A','F','L','K'], // Option 407
  'ABCEFJKL': ['E','J','B','C','A','F','L','K'], // Option 406
  'ABCEGHIJ': ['H','J','B','C','A','G','E','I'], // Option 405
  'ABCEGHIK': ['E','G','B','C','A','H','I','K'], // Option 404
  'ABCEGHIL': ['E','G','B','C','A','H','L','I'], // Option 403
  'ABCEGHJK': ['H','J','B','C','A','G','E','K'], // Option 402
  'ABCEGHJL': ['H','J','B','C','A','G','L','E'], // Option 401
  'ABCEGHKL': ['E','G','B','C','A','H','L','K'], // Option 400
  'ABCEGIJK': ['E','J','B','C','A','G','I','K'], // Option 399
  'ABCEGIJL': ['E','J','B','C','A','G','L','I'], // Option 398
  'ABCEGIKL': ['E','G','B','A','I','C','L','K'], // Option 397
  'ABCEGJKL': ['E','J','B','C','A','G','L','K'], // Option 396
  'ABCEHIJK': ['E','J','B','C','A','H','I','K'], // Option 395
  'ABCEHIJL': ['E','J','B','C','A','H','L','I'], // Option 394
  'ABCEHIKL': ['E','I','B','C','A','H','L','K'], // Option 393
  'ABCEHJKL': ['E','J','B','C','A','H','L','K'], // Option 392
  'ABCEIJKL': ['E','J','B','A','I','C','L','K'], // Option 391
  'ABCFGHIJ': ['H','G','B','C','A','F','I','J'], // Option 390
  'ABCFGHIK': ['H','G','B','C','A','F','I','K'], // Option 389
  'ABCFGHIL': ['H','G','B','C','A','F','L','I'], // Option 388
  'ABCFGHJK': ['H','G','B','C','A','F','J','K'], // Option 387
  'ABCFGHJL': ['H','G','B','C','A','F','L','J'], // Option 386
  'ABCFGHKL': ['H','G','B','C','A','F','L','K'], // Option 385
  'ABCFGIJK': ['C','J','B','F','A','G','I','K'], // Option 384
  'ABCFGIJL': ['C','J','B','F','A','G','L','I'], // Option 383
  'ABCFGIKL': ['I','G','B','C','A','F','L','K'], // Option 382
  'ABCFGJKL': ['C','J','B','F','A','G','L','K'], // Option 381
  'ABCFHIJK': ['H','J','B','C','A','F','I','K'], // Option 380
  'ABCFHIJL': ['H','J','B','C','A','F','L','I'], // Option 379
  'ABCFHIKL': ['H','I','B','C','A','F','L','K'], // Option 378
  'ABCFHJKL': ['H','J','B','C','A','F','L','K'], // Option 377
  'ABCFIJKL': ['I','J','B','C','A','F','L','K'], // Option 376
  'ABCGHIJK': ['H','J','B','C','A','G','I','K'], // Option 375
  'ABCGHIJL': ['H','J','B','C','A','G','L','I'], // Option 374
  'ABCGHIKL': ['I','G','B','C','A','H','L','K'], // Option 373
  'ABCGHJKL': ['H','J','B','C','A','G','L','K'], // Option 372
  'ABCGIJKL': ['I','J','B','C','A','G','L','K'], // Option 371
  'ABCHIJKL': ['I','J','B','C','A','H','L','K'], // Option 370
  'ABDEFGHI': ['H','G','B','D','A','F','E','I'], // Option 369
  'ABDEFGHJ': ['H','G','B','D','A','F','E','J'], // Option 368
  'ABDEFGHK': ['H','G','B','D','A','F','E','K'], // Option 367
  'ABDEFGHL': ['H','G','B','D','A','F','L','E'], // Option 366
  'ABDEFGIJ': ['E','G','B','D','A','F','I','J'], // Option 365
  'ABDEFGIK': ['E','G','B','D','A','F','I','K'], // Option 364
  'ABDEFGIL': ['E','G','B','D','A','F','L','I'], // Option 363
  'ABDEFGJK': ['E','G','B','D','A','F','J','K'], // Option 362
  'ABDEFGJL': ['E','G','B','D','A','F','L','J'], // Option 361
  'ABDEFGKL': ['E','G','B','D','A','F','L','K'], // Option 360
  'ABDEFHIJ': ['H','J','B','D','A','F','E','I'], // Option 359
  'ABDEFHIK': ['H','E','B','D','A','F','I','K'], // Option 358
  'ABDEFHIL': ['H','E','B','D','A','F','L','I'], // Option 357
  'ABDEFHJK': ['H','J','B','D','A','F','E','K'], // Option 356
  'ABDEFHJL': ['H','J','B','D','A','F','L','E'], // Option 355
  'ABDEFHKL': ['H','E','B','D','A','F','L','K'], // Option 354
  'ABDEFIJK': ['E','J','B','D','A','F','I','K'], // Option 353
  'ABDEFIJL': ['E','J','B','D','A','F','L','I'], // Option 352
  'ABDEFIKL': ['E','I','B','D','A','F','L','K'], // Option 351
  'ABDEFJKL': ['E','J','B','D','A','F','L','K'], // Option 350
  'ABDEGHIJ': ['H','J','B','D','A','G','E','I'], // Option 349
  'ABDEGHIK': ['E','G','B','D','A','H','I','K'], // Option 348
  'ABDEGHIL': ['E','G','B','D','A','H','L','I'], // Option 347
  'ABDEGHJK': ['H','J','B','D','A','G','E','K'], // Option 346
  'ABDEGHJL': ['H','J','B','D','A','G','L','E'], // Option 345
  'ABDEGHKL': ['E','G','B','D','A','H','L','K'], // Option 344
  'ABDEGIJK': ['E','J','B','D','A','G','I','K'], // Option 343
  'ABDEGIJL': ['E','J','B','D','A','G','L','I'], // Option 342
  'ABDEGIKL': ['E','G','B','A','I','D','L','K'], // Option 341
  'ABDEGJKL': ['E','J','B','D','A','G','L','K'], // Option 340
  'ABDEHIJK': ['E','J','B','D','A','H','I','K'], // Option 339
  'ABDEHIJL': ['E','J','B','D','A','H','L','I'], // Option 338
  'ABDEHIKL': ['E','I','B','D','A','H','L','K'], // Option 337
  'ABDEHJKL': ['E','J','B','D','A','H','L','K'], // Option 336
  'ABDEIJKL': ['E','J','B','A','I','D','L','K'], // Option 335
  'ABDFGHIJ': ['H','G','B','D','A','F','I','J'], // Option 334
  'ABDFGHIK': ['H','G','B','D','A','F','I','K'], // Option 333
  'ABDFGHIL': ['H','G','B','D','A','F','L','I'], // Option 332
  'ABDFGHJK': ['H','G','B','D','A','F','J','K'], // Option 331
  'ABDFGHJL': ['H','G','B','D','A','F','L','J'], // Option 330
  'ABDFGHKL': ['H','G','B','D','A','F','L','K'], // Option 329
  'ABDFGIJK': ['F','J','B','D','A','G','I','K'], // Option 328
  'ABDFGIJL': ['F','J','B','D','A','G','L','I'], // Option 327
  'ABDFGIKL': ['I','G','B','D','A','F','L','K'], // Option 326
  'ABDFGJKL': ['F','J','B','D','A','G','L','K'], // Option 325
  'ABDFHIJK': ['H','J','B','D','A','F','I','K'], // Option 324
  'ABDFHIJL': ['H','J','B','D','A','F','L','I'], // Option 323
  'ABDFHIKL': ['H','I','B','D','A','F','L','K'], // Option 322
  'ABDFHJKL': ['H','J','B','D','A','F','L','K'], // Option 321
  'ABDFIJKL': ['I','J','B','D','A','F','L','K'], // Option 320
  'ABDGHIJK': ['H','J','B','D','A','G','I','K'], // Option 319
  'ABDGHIJL': ['H','J','B','D','A','G','L','I'], // Option 318
  'ABDGHIKL': ['I','G','B','D','A','H','L','K'], // Option 317
  'ABDGHJKL': ['H','J','B','D','A','G','L','K'], // Option 316
  'ABDGIJKL': ['I','J','B','D','A','G','L','K'], // Option 315
  'ABDHIJKL': ['I','J','B','D','A','H','L','K'], // Option 314
  'ABEFGHIJ': ['H','J','B','F','A','G','E','I'], // Option 313
  'ABEFGHIK': ['E','G','B','F','A','H','I','K'], // Option 312
  'ABEFGHIL': ['E','G','B','F','A','H','L','I'], // Option 311
  'ABEFGHJK': ['H','J','B','F','A','G','E','K'], // Option 310
  'ABEFGHJL': ['H','J','B','F','A','G','L','E'], // Option 309
  'ABEFGHKL': ['E','G','B','F','A','H','L','K'], // Option 308
  'ABEFGIJK': ['E','J','B','F','A','G','I','K'], // Option 307
  'ABEFGIJL': ['E','J','B','F','A','G','L','I'], // Option 306
  'ABEFGIKL': ['E','G','B','A','I','F','L','K'], // Option 305
  'ABEFGJKL': ['E','J','B','F','A','G','L','K'], // Option 304
  'ABEFHIJK': ['E','J','B','F','A','H','I','K'], // Option 303
  'ABEFHIJL': ['E','J','B','F','A','H','L','I'], // Option 302
  'ABEFHIKL': ['E','I','B','F','A','H','L','K'], // Option 301
  'ABEFHJKL': ['E','J','B','F','A','H','L','K'], // Option 300
  'ABEFIJKL': ['E','J','B','A','I','F','L','K'], // Option 299
  'ABEGHIJK': ['E','J','B','A','H','G','I','K'], // Option 298
  'ABEGHIJL': ['E','J','B','A','H','G','L','I'], // Option 297
  'ABEGHIKL': ['E','G','B','A','I','H','L','K'], // Option 296
  'ABEGHJKL': ['E','J','B','A','H','G','L','K'], // Option 295
  'ABEGIJKL': ['E','J','B','A','I','G','L','K'], // Option 294
  'ABEHIJKL': ['E','J','B','A','I','H','L','K'], // Option 293
  'ABFGHIJK': ['H','J','B','F','A','G','I','K'], // Option 292
  'ABFGHIJL': ['H','J','B','F','A','G','L','I'], // Option 291
  'ABFGHIKL': ['H','G','B','A','I','F','L','K'], // Option 290
  'ABFGHJKL': ['H','J','B','F','A','G','L','K'], // Option 289
  'ABFGIJKL': ['I','J','B','F','A','G','L','K'], // Option 288
  'ABFHIJKL': ['H','J','B','A','I','F','L','K'], // Option 287
  'ABGHIJKL': ['H','J','B','A','I','G','L','K'], // Option 286
  'ACDEFGHI': ['H','G','E','C','A','F','D','I'], // Option 285
  'ACDEFGHJ': ['H','G','J','C','A','F','D','E'], // Option 284
  'ACDEFGHK': ['H','G','E','C','A','F','D','K'], // Option 283
  'ACDEFGHL': ['H','G','F','C','A','D','L','E'], // Option 282
  'ACDEFGIJ': ['C','G','J','D','A','F','E','I'], // Option 281
  'ACDEFGIK': ['C','G','E','D','A','F','I','K'], // Option 280
  'ACDEFGIL': ['C','G','E','D','A','F','L','I'], // Option 279
  'ACDEFGJK': ['C','G','J','D','A','F','E','K'], // Option 278
  'ACDEFGJL': ['C','G','J','D','A','F','L','E'], // Option 277
  'ACDEFGKL': ['C','G','E','D','A','F','L','K'], // Option 276
  'ACDEFHIJ': ['H','J','E','C','A','F','D','I'], // Option 275
  'ACDEFHIK': ['H','E','F','C','A','D','I','K'], // Option 274
  'ACDEFHIL': ['H','E','F','C','A','D','L','I'], // Option 273
  'ACDEFHJK': ['H','J','E','C','A','F','D','K'], // Option 272
  'ACDEFHJL': ['H','J','F','C','A','D','L','E'], // Option 271
  'ACDEFHKL': ['H','E','F','C','A','D','L','K'], // Option 270
  'ACDEFIJK': ['C','J','E','D','A','F','I','K'], // Option 269
  'ACDEFIJL': ['C','J','E','D','A','F','L','I'], // Option 268
  'ACDEFIKL': ['C','E','I','D','A','F','L','K'], // Option 267
  'ACDEFJKL': ['C','J','E','D','A','F','L','K'], // Option 266
  'ACDEGHIJ': ['H','G','J','C','A','D','E','I'], // Option 265
  'ACDEGHIK': ['H','G','E','C','A','D','I','K'], // Option 264
  'ACDEGHIL': ['H','G','E','C','A','D','L','I'], // Option 263
  'ACDEGHJK': ['H','G','J','C','A','D','E','K'], // Option 262
  'ACDEGHJL': ['H','G','J','C','A','D','L','E'], // Option 261
  'ACDEGHKL': ['H','G','E','C','A','D','L','K'], // Option 260
  'ACDEGIJK': ['E','G','J','C','A','D','I','K'], // Option 259
  'ACDEGIJL': ['E','G','J','C','A','D','L','I'], // Option 258
  'ACDEGIKL': ['E','G','I','C','A','D','L','K'], // Option 257
  'ACDEGJKL': ['E','G','J','C','A','D','L','K'], // Option 256
  'ACDEHIJK': ['H','J','E','C','A','D','I','K'], // Option 255
  'ACDEHIJL': ['H','J','E','C','A','D','L','I'], // Option 254
  'ACDEHIKL': ['H','E','I','C','A','D','L','K'], // Option 253
  'ACDEHJKL': ['H','J','E','C','A','D','L','K'], // Option 252
  'ACDEIJKL': ['E','J','I','C','A','D','L','K'], // Option 251
  'ACDFGHIJ': ['H','G','J','C','A','F','D','I'], // Option 250
  'ACDFGHIK': ['H','G','F','C','A','D','I','K'], // Option 249
  'ACDFGHIL': ['H','G','F','C','A','D','L','I'], // Option 248
  'ACDFGHJK': ['H','G','J','C','A','F','D','K'], // Option 247
  'ACDFGHJL': ['C','G','J','D','A','F','L','H'], // Option 246
  'ACDFGHKL': ['H','G','F','C','A','D','L','K'], // Option 245
  'ACDFGIJK': ['C','G','J','D','A','F','I','K'], // Option 244
  'ACDFGIJL': ['C','G','J','D','A','F','L','I'], // Option 243
  'ACDFGIKL': ['C','G','I','D','A','F','L','K'], // Option 242
  'ACDFGJKL': ['C','G','J','D','A','F','L','K'], // Option 241
  'ACDFHIJK': ['H','J','F','C','A','D','I','K'], // Option 240
  'ACDFHIJL': ['H','J','F','C','A','D','L','I'], // Option 239
  'ACDFHIKL': ['H','F','I','C','A','D','L','K'], // Option 238
  'ACDFHJKL': ['H','J','F','C','A','D','L','K'], // Option 237
  'ACDFIJKL': ['C','J','I','D','A','F','L','K'], // Option 236
  'ACDGHIJK': ['H','G','J','C','A','D','I','K'], // Option 235
  'ACDGHIJL': ['H','G','J','C','A','D','L','I'], // Option 234
  'ACDGHIKL': ['H','G','I','C','A','D','L','K'], // Option 233
  'ACDGHJKL': ['H','G','J','C','A','D','L','K'], // Option 232
  'ACDGIJKL': ['I','G','J','C','A','D','L','K'], // Option 231
  'ACDHIJKL': ['H','J','I','C','A','D','L','K'], // Option 230
  'ACEFGHIJ': ['H','G','J','C','A','F','E','I'], // Option 229
  'ACEFGHIK': ['H','G','E','C','A','F','I','K'], // Option 228
  'ACEFGHIL': ['H','G','E','C','A','F','L','I'], // Option 227
  'ACEFGHJK': ['H','G','J','C','A','F','E','K'], // Option 226
  'ACEFGHJL': ['H','G','J','C','A','F','L','E'], // Option 225
  'ACEFGHKL': ['H','G','E','C','A','F','L','K'], // Option 224
  'ACEFGIJK': ['E','G','J','C','A','F','I','K'], // Option 223
  'ACEFGIJL': ['E','G','J','C','A','F','L','I'], // Option 222
  'ACEFGIKL': ['E','G','I','C','A','F','L','K'], // Option 221
  'ACEFGJKL': ['E','G','J','C','A','F','L','K'], // Option 220
  'ACEFHIJK': ['H','J','E','C','A','F','I','K'], // Option 219
  'ACEFHIJL': ['H','J','E','C','A','F','L','I'], // Option 218
  'ACEFHIKL': ['H','E','I','C','A','F','L','K'], // Option 217
  'ACEFHJKL': ['H','J','E','C','A','F','L','K'], // Option 216
  'ACEFIJKL': ['E','J','I','C','A','F','L','K'], // Option 215
  'ACEGHIJK': ['E','G','J','C','A','H','I','K'], // Option 214
  'ACEGHIJL': ['E','G','J','C','A','H','L','I'], // Option 213
  'ACEGHIKL': ['E','G','I','C','A','H','L','K'], // Option 212
  'ACEGHJKL': ['E','G','J','C','A','H','L','K'], // Option 211
  'ACEGIJKL': ['E','J','I','C','A','G','L','K'], // Option 210
  'ACEHIJKL': ['E','J','I','C','A','H','L','K'], // Option 209
  'ACFGHIJK': ['H','G','J','C','A','F','I','K'], // Option 208
  'ACFGHIJL': ['H','G','J','C','A','F','L','I'], // Option 207
  'ACFGHIKL': ['H','G','I','C','A','F','L','K'], // Option 206
  'ACFGHJKL': ['H','G','J','C','A','F','L','K'], // Option 205
  'ACFGIJKL': ['I','G','J','C','A','F','L','K'], // Option 204
  'ACFHIJKL': ['H','J','I','C','A','F','L','K'], // Option 203
  'ACGHIJKL': ['H','J','I','C','A','G','L','K'], // Option 202
  'ADEFGHIJ': ['H','G','J','D','A','F','E','I'], // Option 201
  'ADEFGHIK': ['H','G','E','D','A','F','I','K'], // Option 200
  'ADEFGHIL': ['H','G','E','D','A','F','L','I'], // Option 199
  'ADEFGHJK': ['H','G','J','D','A','F','E','K'], // Option 198
  'ADEFGHJL': ['H','G','J','D','A','F','L','E'], // Option 197
  'ADEFGHKL': ['H','G','E','D','A','F','L','K'], // Option 196
  'ADEFGIJK': ['E','G','J','D','A','F','I','K'], // Option 195
  'ADEFGIJL': ['E','G','J','D','A','F','L','I'], // Option 194
  'ADEFGIKL': ['E','G','I','D','A','F','L','K'], // Option 193
  'ADEFGJKL': ['E','G','J','D','A','F','L','K'], // Option 192
  'ADEFHIJK': ['H','J','E','D','A','F','I','K'], // Option 191
  'ADEFHIJL': ['H','J','E','D','A','F','L','I'], // Option 190
  'ADEFHIKL': ['H','E','I','D','A','F','L','K'], // Option 189
  'ADEFHJKL': ['H','J','E','D','A','F','L','K'], // Option 188
  'ADEFIJKL': ['E','J','I','D','A','F','L','K'], // Option 187
  'ADEGHIJK': ['E','G','J','D','A','H','I','K'], // Option 186
  'ADEGHIJL': ['E','G','J','D','A','H','L','I'], // Option 185
  'ADEGHIKL': ['E','G','I','D','A','H','L','K'], // Option 184
  'ADEGHJKL': ['E','G','J','D','A','H','L','K'], // Option 183
  'ADEGIJKL': ['E','J','I','D','A','G','L','K'], // Option 182
  'ADEHIJKL': ['E','J','I','D','A','H','L','K'], // Option 181
  'ADFGHIJK': ['H','G','J','D','A','F','I','K'], // Option 180
  'ADFGHIJL': ['H','G','J','D','A','F','L','I'], // Option 179
  'ADFGHIKL': ['H','G','I','D','A','F','L','K'], // Option 178
  'ADFGHJKL': ['H','G','J','D','A','F','L','K'], // Option 177
  'ADFGIJKL': ['I','G','J','D','A','F','L','K'], // Option 176
  'ADFHIJKL': ['H','J','I','D','A','F','L','K'], // Option 175
  'ADGHIJKL': ['H','J','I','D','A','G','L','K'], // Option 174
  'AEFGHIJK': ['E','G','J','F','A','H','I','K'], // Option 173
  'AEFGHIJL': ['E','G','J','F','A','H','L','I'], // Option 172
  'AEFGHIKL': ['E','G','I','F','A','H','L','K'], // Option 171
  'AEFGHJKL': ['E','G','J','F','A','H','L','K'], // Option 170
  'AEFGIJKL': ['E','J','I','F','A','G','L','K'], // Option 169
  'AEFHIJKL': ['E','J','I','F','A','H','L','K'], // Option 168
  'AEGHIJKL': ['E','J','I','A','H','G','L','K'], // Option 167
  'AFGHIJKL': ['H','J','I','F','A','G','L','K'], // Option 166
  'BCDEFGHI': ['C','G','B','D','H','F','E','I'], // Option 165
  'BCDEFGHJ': ['H','G','B','C','J','F','D','E'], // Option 164
  'BCDEFGHK': ['C','G','B','D','H','F','E','K'], // Option 163
  'BCDEFGHL': ['C','G','B','D','H','F','L','E'], // Option 162
  'BCDEFGIJ': ['C','G','B','D','J','F','E','I'], // Option 161
  'BCDEFGIK': ['C','G','B','D','E','F','I','K'], // Option 160
  'BCDEFGIL': ['C','G','B','D','E','F','L','I'], // Option 159
  'BCDEFGJK': ['C','G','B','D','J','F','E','K'], // Option 158
  'BCDEFGJL': ['C','G','B','D','J','F','L','E'], // Option 157
  'BCDEFGKL': ['C','G','B','D','E','F','L','K'], // Option 156
  'BCDEFHIJ': ['C','J','B','D','H','F','E','I'], // Option 155
  'BCDEFHIK': ['C','E','B','D','H','F','I','K'], // Option 154
  'BCDEFHIL': ['C','E','B','D','H','F','L','I'], // Option 153
  'BCDEFHJK': ['C','J','B','D','H','F','E','K'], // Option 152
  'BCDEFHJL': ['C','J','B','D','H','F','L','E'], // Option 151
  'BCDEFHKL': ['C','E','B','D','H','F','L','K'], // Option 150
  'BCDEFIJK': ['C','J','B','D','E','F','I','K'], // Option 149
  'BCDEFIJL': ['C','J','B','D','E','F','L','I'], // Option 148
  'BCDEFIKL': ['C','E','B','D','I','F','L','K'], // Option 147
  'BCDEFJKL': ['C','J','B','D','E','F','L','K'], // Option 146
  'BCDEGHIJ': ['H','G','B','C','J','D','E','I'], // Option 145
  'BCDEGHIK': ['E','G','B','C','H','D','I','K'], // Option 144
  'BCDEGHIL': ['E','G','B','C','H','D','L','I'], // Option 143
  'BCDEGHJK': ['H','G','B','C','J','D','E','K'], // Option 142
  'BCDEGHJL': ['H','G','B','C','J','D','L','E'], // Option 141
  'BCDEGHKL': ['E','G','B','C','H','D','L','K'], // Option 140
  'BCDEGIJK': ['E','G','B','C','J','D','I','K'], // Option 139
  'BCDEGIJL': ['E','G','B','C','J','D','L','I'], // Option 138
  'BCDEGIKL': ['E','G','B','C','I','D','L','K'], // Option 137
  'BCDEGJKL': ['E','G','B','C','J','D','L','K'], // Option 136
  'BCDEHIJK': ['E','J','B','C','H','D','I','K'], // Option 135
  'BCDEHIJL': ['E','J','B','C','H','D','L','I'], // Option 134
  'BCDEHIKL': ['E','I','B','C','H','D','L','K'], // Option 133
  'BCDEHJKL': ['E','J','B','C','H','D','L','K'], // Option 132
  'BCDEIJKL': ['E','J','B','C','I','D','L','K'], // Option 131
  'BCDFGHIJ': ['H','G','B','C','J','F','D','I'], // Option 130
  'BCDFGHIK': ['C','G','B','D','H','F','I','K'], // Option 129
  'BCDFGHIL': ['C','G','B','D','H','F','L','I'], // Option 128
  'BCDFGHJK': ['H','G','B','C','J','F','D','K'], // Option 127
  'BCDFGHJL': ['C','G','B','D','H','F','L','J'], // Option 126
  'BCDFGHKL': ['C','G','B','D','H','F','L','K'], // Option 125
  'BCDFGIJK': ['C','G','B','D','J','F','I','K'], // Option 124
  'BCDFGIJL': ['C','G','B','D','J','F','L','I'], // Option 123
  'BCDFGIKL': ['C','G','B','D','I','F','L','K'], // Option 122
  'BCDFGJKL': ['C','G','B','D','J','F','L','K'], // Option 121
  'BCDFHIJK': ['C','J','B','D','H','F','I','K'], // Option 120
  'BCDFHIJL': ['C','J','B','D','H','F','L','I'], // Option 119
  'BCDFHIKL': ['C','I','B','D','H','F','L','K'], // Option 118
  'BCDFHJKL': ['C','J','B','D','H','F','L','K'], // Option 117
  'BCDFIJKL': ['C','J','B','D','I','F','L','K'], // Option 116
  'BCDGHIJK': ['H','G','B','C','J','D','I','K'], // Option 115
  'BCDGHIJL': ['H','G','B','C','J','D','L','I'], // Option 114
  'BCDGHIKL': ['H','G','B','C','I','D','L','K'], // Option 113
  'BCDGHJKL': ['H','G','B','C','J','D','L','K'], // Option 112
  'BCDGIJKL': ['I','G','B','C','J','D','L','K'], // Option 111
  'BCDHIJKL': ['H','J','B','C','I','D','L','K'], // Option 110
  'BCEFGHIJ': ['H','G','B','C','J','F','E','I'], // Option 109
  'BCEFGHIK': ['E','G','B','C','H','F','I','K'], // Option 108
  'BCEFGHIL': ['E','G','B','C','H','F','L','I'], // Option 107
  'BCEFGHJK': ['H','G','B','C','J','F','E','K'], // Option 106
  'BCEFGHJL': ['H','G','B','C','J','F','L','E'], // Option 105
  'BCEFGHKL': ['E','G','B','C','H','F','L','K'], // Option 104
  'BCEFGIJK': ['E','G','B','C','J','F','I','K'], // Option 103
  'BCEFGIJL': ['E','G','B','C','J','F','L','I'], // Option 102
  'BCEFGIKL': ['E','G','B','C','I','F','L','K'], // Option 101
  'BCEFGJKL': ['E','G','B','C','J','F','L','K'], // Option 100
  'BCEFHIJK': ['E','J','B','C','H','F','I','K'], // Option 99
  'BCEFHIJL': ['E','J','B','C','H','F','L','I'], // Option 98
  'BCEFHIKL': ['E','I','B','C','H','F','L','K'], // Option 97
  'BCEFHJKL': ['E','J','B','C','H','F','L','K'], // Option 96
  'BCEFIJKL': ['E','J','B','C','I','F','L','K'], // Option 95
  'BCEGHIJK': ['E','J','B','C','H','G','I','K'], // Option 94
  'BCEGHIJL': ['E','J','B','C','H','G','L','I'], // Option 93
  'BCEGHIKL': ['E','G','B','C','I','H','L','K'], // Option 92
  'BCEGHJKL': ['E','J','B','C','H','G','L','K'], // Option 91
  'BCEGIJKL': ['E','J','B','C','I','G','L','K'], // Option 90
  'BCEHIJKL': ['E','J','B','C','I','H','L','K'], // Option 89
  'BCFGHIJK': ['H','G','B','C','J','F','I','K'], // Option 88
  'BCFGHIJL': ['H','G','B','C','J','F','L','I'], // Option 87
  'BCFGHIKL': ['H','G','B','C','I','F','L','K'], // Option 86
  'BCFGHJKL': ['H','G','B','C','J','F','L','K'], // Option 85
  'BCFGIJKL': ['I','G','B','C','J','F','L','K'], // Option 84
  'BCFHIJKL': ['H','J','B','C','I','F','L','K'], // Option 83
  'BCGHIJKL': ['H','J','B','C','I','G','L','K'], // Option 82
  'BDEFGHIJ': ['H','G','B','D','J','F','E','I'], // Option 81
  'BDEFGHIK': ['E','G','B','D','H','F','I','K'], // Option 80
  'BDEFGHIL': ['E','G','B','D','H','F','L','I'], // Option 79
  'BDEFGHJK': ['H','G','B','D','J','F','E','K'], // Option 78
  'BDEFGHJL': ['H','G','B','D','J','F','L','E'], // Option 77
  'BDEFGHKL': ['E','G','B','D','H','F','L','K'], // Option 76
  'BDEFGIJK': ['E','G','B','D','J','F','I','K'], // Option 75
  'BDEFGIJL': ['E','G','B','D','J','F','L','I'], // Option 74
  'BDEFGIKL': ['E','G','B','D','I','F','L','K'], // Option 73
  'BDEFGJKL': ['E','G','B','D','J','F','L','K'], // Option 72
  'BDEFHIJK': ['E','J','B','D','H','F','I','K'], // Option 71
  'BDEFHIJL': ['E','J','B','D','H','F','L','I'], // Option 70
  'BDEFHIKL': ['E','I','B','D','H','F','L','K'], // Option 69
  'BDEFHJKL': ['E','J','B','D','H','F','L','K'], // Option 68
  'BDEFIJKL': ['E','J','B','D','I','F','L','K'], // Option 67
  'BDEGHIJK': ['E','J','B','D','H','G','I','K'], // Option 66
  'BDEGHIJL': ['E','J','B','D','H','G','L','I'], // Option 65
  'BDEGHIKL': ['E','G','B','D','I','H','L','K'], // Option 64
  'BDEGHJKL': ['E','J','B','D','H','G','L','K'], // Option 63
  'BDEGIJKL': ['E','J','B','D','I','G','L','K'], // Option 62
  'BDEHIJKL': ['E','J','B','D','I','H','L','K'], // Option 61
  'BDFGHIJK': ['H','G','B','D','J','F','I','K'], // Option 60
  'BDFGHIJL': ['H','G','B','D','J','F','L','I'], // Option 59
  'BDFGHIKL': ['H','G','B','D','I','F','L','K'], // Option 58
  'BDFGHJKL': ['H','G','B','D','J','F','L','K'], // Option 57
  'BDFGIJKL': ['I','G','B','D','J','F','L','K'], // Option 56
  'BDFHIJKL': ['H','J','B','D','I','F','L','K'], // Option 55
  'BDGHIJKL': ['H','J','B','D','I','G','L','K'], // Option 54
  'BEFGHIJK': ['E','J','B','F','H','G','I','K'], // Option 53
  'BEFGHIJL': ['E','J','B','F','H','G','L','I'], // Option 52
  'BEFGHIKL': ['E','G','B','F','I','H','L','K'], // Option 51
  'BEFGHJKL': ['E','J','B','F','H','G','L','K'], // Option 50
  'BEFGIJKL': ['E','J','B','F','I','G','L','K'], // Option 49
  'BEFHIJKL': ['E','J','B','F','I','H','L','K'], // Option 48
  'BEGHIJKL': ['E','J','I','B','H','G','L','K'], // Option 47
  'BFGHIJKL': ['H','J','B','F','I','G','L','K'], // Option 46
  'CDEFGHIJ': ['C','G','J','D','H','F','E','I'], // Option 45
  'CDEFGHIK': ['C','G','E','D','H','F','I','K'], // Option 44
  'CDEFGHIL': ['C','G','E','D','H','F','L','I'], // Option 43
  'CDEFGHJK': ['C','G','J','D','H','F','E','K'], // Option 42
  'CDEFGHJL': ['C','G','J','D','H','F','L','E'], // Option 41
  'CDEFGHKL': ['C','G','E','D','H','F','L','K'], // Option 40
  'CDEFGIJK': ['C','G','E','D','J','F','I','K'], // Option 39
  'CDEFGIJL': ['C','G','E','D','J','F','L','I'], // Option 38
  'CDEFGIKL': ['C','G','E','D','I','F','L','K'], // Option 37
  'CDEFGJKL': ['C','G','E','D','J','F','L','K'], // Option 36
  'CDEFHIJK': ['C','J','E','D','H','F','I','K'], // Option 35
  'CDEFHIJL': ['C','J','E','D','H','F','L','I'], // Option 34
  'CDEFHIKL': ['C','E','I','D','H','F','L','K'], // Option 33
  'CDEFHJKL': ['C','J','E','D','H','F','L','K'], // Option 32
  'CDEFIJKL': ['C','J','E','D','I','F','L','K'], // Option 31
  'CDEGHIJK': ['E','G','J','C','H','D','I','K'], // Option 30
  'CDEGHIJL': ['E','G','J','C','H','D','L','I'], // Option 29
  'CDEGHIKL': ['E','G','I','C','H','D','L','K'], // Option 28
  'CDEGHJKL': ['E','G','J','C','H','D','L','K'], // Option 27
  'CDEGIJKL': ['E','G','I','C','J','D','L','K'], // Option 26
  'CDEHIJKL': ['E','J','I','C','H','D','L','K'], // Option 25
  'CDFGHIJK': ['C','G','J','D','H','F','I','K'], // Option 24
  'CDFGHIJL': ['C','G','J','D','H','F','L','I'], // Option 23
  'CDFGHIKL': ['C','G','I','D','H','F','L','K'], // Option 22
  'CDFGHJKL': ['C','G','J','D','H','F','L','K'], // Option 21
  'CDFGIJKL': ['C','G','I','D','J','F','L','K'], // Option 20
  'CDFHIJKL': ['C','J','I','D','H','F','L','K'], // Option 19
  'CDGHIJKL': ['H','G','I','C','J','D','L','K'], // Option 18
  'CEFGHIJK': ['E','G','J','C','H','F','I','K'], // Option 17
  'CEFGHIJL': ['E','G','J','C','H','F','L','I'], // Option 16
  'CEFGHIKL': ['E','G','I','C','H','F','L','K'], // Option 15
  'CEFGHJKL': ['E','G','J','C','H','F','L','K'], // Option 14
  'CEFGIJKL': ['E','G','I','C','J','F','L','K'], // Option 13
  'CEFHIJKL': ['E','J','I','C','H','F','L','K'], // Option 12
  'CEGHIJKL': ['E','J','I','C','H','G','L','K'], // Option 11
  'CFGHIJKL': ['H','G','I','C','J','F','L','K'], // Option 10
  'DEFGHIJK': ['E','G','J','D','H','F','I','K'], // Option 9
  'DEFGHIJL': ['E','G','J','D','H','F','L','I'], // Option 8
  'DEFGHIKL': ['E','G','I','D','H','F','L','K'], // Option 7
  'DEFGHJKL': ['E','G','J','D','H','F','L','K'], // Option 6
  'DEFGIJKL': ['E','G','I','D','J','F','L','K'], // Option 5
  'DEFHIJKL': ['E','J','I','D','H','F','L','K'], // Option 4
  'DEGHIJKL': ['E','J','I','D','H','G','L','K'], // Option 3
  'DFGHIJKL': ['H','G','I','D','J','F','L','K'], // Option 2
  'EFGHIJKL': ['E','J','I','F','H','G','L','K'], // Option 1
};

/**
 * Look up the third-place assignment for a given combination key.
 * Returns array of group letters indexed as [1A, 1B, 1D, 1E, 1G, 1I, 1K, 1L]
 */
export function lookupFIFAMatrix(key: string): string[] | null {
  return FIFA_MATRIX[key] ?? null;
}
